
services:
  api:
    build: ../api
    ports:
      - "5000:5000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  api-to-sql:
    build: ../api
    command: python app/scripts/data_api_to_postgres.py
    depends_on:
      - api
      - postgres


  spark-extract:
    image: bitnamilegacy/spark:latest
    volumes:
      - ../spark:/jobs
      - ../spark/mapping.csv:/app/mapping.csv
      - ./postgresql-42.7.3.jar:/opt/bitnami/spark/jars/postgresql-42.7.3.jar
    working_dir: /jobs
    command: ["python", "jobs/extract_location_information.py"]
    depends_on:
      - api
      - postgres
      - api-to-sql


      # spark-consumer:
      #   image: bitnamilegacy/spark:3.4.1
      #   environment:
      #     - PYSPARK_PYTHON=python3
      #     - HOME=/tmp
      #   volumes:
      #     - ../spark:/jobs
      #     - ./spark-sql-kafka-0-10_2.12-3.4.1.jar:/opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.4.1.jar
      #     - ./postgresql-42.7.3.jar:/opt/bitnami/spark/jars/postgresql-42.7.3.jar
      #   working_dir: /jobs
      #   entrypoint: ["/bin/bash", "-c", "pip install py4j==0.10.9.7 && python jobs/consumer_orders_stream.py"]
      #   depends_on:
      #     - postgres
      #     - kafka
      #     - zookeeper

      # kafka:
      #   image: confluentinc/cp-kafka:7.4.0
      #   ports:
      #     - "9092:9092"
      #   environment:
      #     KAFKA_BROKER_ID: 1
      #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #   depends_on:
      #     - zookeeper

      # zookeeper:
      #   image: confluentinc/cp-zookeeper:7.4.0
      #   ports:
      #     - "2181:2181"
      #   environment:
      #     ZOOKEEPER_CLIENT_PORT: 2181
      #     ZOOKEEPER_TICK_TIME: 2000

      # producer:
      #   build: ../kafka/producers
      #   command: ["python", "producer.py"]
      #   depends_on:
      #     - kafka
      #   restart: on-failure
